AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Echos Lambda Executor.

Globals:
  Function: 
    PermissionsBoundary: PERMISSIONS_BOUNDARY_ARN

Resources:
  EchosExecutor:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: EchosExecutor
      Handler: src/app.lambda_handler
      CodeUri: .
      Runtime: python3.8
      MemorySize: 512
      Timeout: 300
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 's3:ListBucket'
                - 's3:GetObject'
                - 's3:PutObject'
                - 's3:DeleteObject'
                - 's3:*MultipartUpload*'
              Resource: ECHOS_BUCKET_ARN
